### ISSUE TITLE
Create a Landing Page

### ISSUE THREAD

**Issue by rahman-ashik** [rahman-ashik/BookingApp#1]
Get ideas from https://www.priceline.com/

- [x] Add Global Top Navbar
- [x] Add Banner with Search Component Overlay 
- [x] Add Global Bottom Menu

**Comment by MushfiqPlabon** [comment]
![screencapture-localhost-3000-2021-08-19-00_05_31](https://user-images.githubusercontent.com/43218949/129949764-dedb4e7d-276f-48ff-a700-04d873e58d98.png)
Still needs some makeover.
